version: '3'

services:
  nginx:
    image: nginx:1.19.10
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - ../../project/public:/var/www/html
      - ../../project/storage/app/public:/var/www/html/storage
    depends_on:
      - php-fpm
    ports:
      - 8000:80
  php-fpm:
    build: 
      context: ./
      dockerfile: ./php/Dockerfile
    volumes:
        - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        - ../../:/var/workspace
  mysql:
    image: mysql:8.1
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=tokumine
      - MYSQL_PASSWORD=tokumine
      - TZ='Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    # ports:
    #   - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - mysql
    ports:
      - 4040:80